name: Build FFmpeg Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: >-
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make
            mingw-w64-x86_64-nasm

      - name: Debug toolchain
        shell: msys2 {0}
        run: |
          echo "===== TOOL CHECK ====="
          which gcc
          which g++
          which nm || true
          which llvm-nm || true
          which nasm || true
          ls /mingw64/bin | grep nm || true
          echo "======================"

      - name: Build FFmpeg
        shell: msys2 {0}
        run: |
          chmod +x build_ffmpeg_windows.sh
          ./build_ffmpeg_windows.sh
